"""add rate

Revision ID: 203d72b7f1c9
Revises: cf3752361f1c
Create Date: 2023-01-22 20:51:15.302465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203d72b7f1c9'
down_revision = 'cf3752361f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_model', schema=None) as batch_op:
        batch_op.drop_column('rate')

    # ### end Alembic commands ###
